# General listeners
listener 1883
protocol mqtt

listener 9001
protocol websockets

# Bypasses access controls for immediate local network testing
allow_anonymous true

# Persistence parameters
persistence true
persistence_location /mosquitto/data/

# Telemetry logging paths
log_dest file /mosquitto/log/mosquitto.log